CREATE TABLE IF NOT EXISTS orders(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    FOREIGN KEY user_id REFERENCES orders(id) ON UPDATE CASCADE,
    status_id INTEGER NOT NULL,
    FOREIGN KEY status_id REFERENCES orders(id) ON UPDATE CASCADE,
);