CREATE TABLE IF NOT EXISTS products(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(36),
    description VARCHAR(140) UNIQUE,
    category_id INTEGER NOT NULL,
    FOREIGN KEY category_id REFERENCES products(id) ON UPDATE SET NULL
);